version: "2"

services:
  frontend:
    volumes:
      - ".:/usr/src/app"
    command: watchmedo auto-restart -d /usr/src/app -p "*.py" -D -R -- gunicorn -k gevent -b 0.0.0.0:5002 xssp_api.application:app
    environment:
      - XSSP_API_SETTINGS=/usr/src/app/dev_settings.py

  celery:
    volumes:
      - ".:/usr/src/app"
    command: watchmedo auto-restart -d /usr/src/app -p "*.py" -D -R -- celery -A xssp_api.application:celery worker -B -n xssp.%n
    environment:
      - XSSP_API_SETTINGS=/usr/src/app/dev_settings.py
